# TODO: check if there's a way make sure this playbook isn't run without setup
- name: Traefik install
  hosts: swarm
  become: true
  tasks: 
    - name: Start Traefik container
      community.docker.docker_container:
        name: traefik
        image: traefik:3.7.13
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
          - "443:443"
          - "8080:8080"