# TODO: check if there's a way make sure this playbook isn't run without setup
- name: Traefik install
  hosts: swarm
  become: true
  tasks: 
    - name: Create Traefik directory
      ansible.builtin.file:
        path: /etc/traefik
        state: directory
        mode: '0755'

    - name: Copy Traefik configuration
      ansible.builtin.copy:
        src: traefik.yaml
        dest: /etc/traefik/traefik.yaml
        mode: '0644'
      # TODO: remove restart traefik once static config if finalized. Remove handler too
      notify: Restart Traefik

    - name: Start Traefik container
      community.docker.docker_container:
        name: traefik
        image: traefik:3.7.13
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        volumes:
          - "/etc/traefik:/etc/traefik:ro"

  handlers:
    - name: Restart Traefik
      community.docker.docker_container:
        name: traefik
        state: started
        restart: true